sudo: required
services:
  - 'docker'
before_install:
  - 'chmod +x build.sh'
  - './.travis/main.sh'

script:
  - 'make test'
  - 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

# don't notify me when things fail
notifications:
  email: false