dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t diegotony/client-micro .
      - docker images
      - docker push $DOCKER_USERNAME/client-micro:latest
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/client-micro:latest
    - script: docker run --rm $DOCKER_USERNAME/client-micro:latest