dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t diegotony/client-micro .
      - docker images
      - docker tag client-micro $DOCKER_USERNAME/client-micro
      - docker push $DOCKER_USERNAME/client-micro
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/client-micro
    - script: docker run --rm $DOCKER_USERNAME/client-micro