dist: trusty

sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t diegotony/orden-micro .
      after_success:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/orden-micro:latest
