dist: trusty
sudo: required
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t diegotony/client-micro .
      after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker push $DOCKER_USERNAME/client-micro:latest
